---

name: Update

"on":
  schedule:
    # Run on the 10th of each month at noon.
    - cron: "00 12 15 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TEMPLATE_REPOSITORY: "dmitriysafronov/ansible_role-template"

jobs:

  test:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        if: ${{ github.repository != env.TEMPLATE_REPOSITORY }}
        uses: actions/checkout@v3

      - name: Check out template repo
        if: ${{ github.repository != env.TEMPLATE_REPOSITORY }}
        uses: actions/checkout@v3
        with:
          repository: env.TEMPLATE_REPOSITORY

      - uses: peter-evans/create-pull-request@v3
        if: ${{ github.repository != env.TEMPLATE_REPOSITORY }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "update"
          delete-branch: true
          title: "chore(deps): upgrade from template"
          signoff: true
          committer: "nobody <nobody@users.noreply.github.com>"
          author: "nobody <nobody@users.noreply.github.com>"
          commit-message: "chore(deps): upgrade from template"
          body: |
            Upgrade from template
          draft: false
